# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.47.0"

default_platform :android

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(
      task: "jacocoTestReport"
    )
  end

  desc "Submit a new Beta Build to Fabric Beta"
  lane :deploy_beta do
    ensure_git_status_clean

    # build debug app
    gradle(task: "clean") 
    gradle(
      task: "assemble",
      build_type: "Debug",
    )
  
    increment_version_code(
      gradle_file_path: "example/build.gradle",
    )

    # Generate changelogs from git commits
    changelog_from_git_commits

    # Upload to crashlytics
    crashlytics(
      api_token: ENV["FABRIC_API_TOKEN"],
      build_secret: ENV["FABRIC_BUILD_SECRET"],
      groups: ENV["FABRIC_GROUPS"]
    )
  end

  desc "Deploy a new version of framework to maven repository"
  lane :release do |lane|
    
    if !lane[:version]
      raise "No version specified!".red
    end
    
    #ensure_git_status_clean
    #ensure_git_branch

    version = lane[:version]
    gradle(task: "publish")

    s3_update_acl(
      region: ENV['S3_REGION'],
      bucket: ENV['S3_BUCKET'],
      access_key: ENV['S3_ACCESS_KEY'],
      secret_access_key: ENV['S3_SECRET_ACCESS_KEY'],
      version: version
    )
  end

  error do |lane, exception|

  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
